### ISSUE TITLE
Error on activation

### ISSUE THREAD

**Issue by l-fuller** [grrr-amsterdam/simply-static-deploy#29]
I've installed as per instructions (from the root of my install), the plugin installs to the correct directory, but when trying to activate I get the following error.

( ! ) Fatal error: Uncaught Error: Class 'Grrr\SimplyStaticDeploy\SimplyStaticDeploy' not found in /app/public/wp-content/plugins/simply-static-deploy/simply-static-deploy.php on line 25
( ! ) Error: Class 'Grrr\SimplyStaticDeploy\SimplyStaticDeploy' not found in /app/public/wp-content/plugins/simply-static-deploy/simply-static-deploy.php on line 25
Call Stack
#	Time	Memory	Function	Location
1	0.0001	402440	{main}( )	.../plugins.php:0
2	0.1455	7230584	plugin_sandbox_scrape( )	.../plugins.php:177
3	0.1455	7230936	include( '/app/public/wp-content/plugins/simply-static-deploy/simply-static-deploy.php' )	.../plugin.php:2255

**Comment by MJoeWatson** [comment]
Unfortunately I've been having the issue as well. After installing the plugin successfully, I was unable to activate it. Are there issues with specific versions of PHP or Wordpress?

**Comment by schoenkaft** [comment]
@l-fuller it seems you haven't included the Composer autoloader in your project. I've updated the readme with a small note about this in the installation section.

It's not merged to `master` yet, but can be seen here: https://github.com/grrr-amsterdam/simply-static-deploy/tree/autoloader-readme#installation

Let me know if this resolves your problem 👍

**Comment by artipixel** [comment]
I'm also having this issue as many others and it's still present. 
Can't activate the plugin no matter what, did everything by the book, installed it again, autoload is in wp-config, simply static plugin installed. Everything is fine. accept it wont work :(

**Comment by jason-lavigne-healthsaas** [comment]
Hi,

I am also running in to this issue, can you provide some guidance on the required permissions?

It appears that for me, your include files are not loading...the autoload.php is running.

Also my project did not have composer used, however I did create the composer.json in the root (where wp-config.php lives) and included only your extra info and the plugin installed where it should and the vendor folder exists as expected.

Really looking forward to getting this to run, for the life of me I cannot find the issue....

**Comment by elreydetoda** [comment]
@jason-lavigne-healthsaas, this worked for me: https://github.com/grrr-amsterdam/simply-static-deploy/issues/33#issuecomment-635293858
